name: C/C++ CI2


on:
  workflow_dispatch:
  schedule:
       - cron: 0 05 * * *
       
jobs:
  build-LLVM-14:
    name: C/C++ CI3
    runs-on: windows-latest
    steps:
      - name: Get LLVM
        uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Rebuild and Install LLVM
        shell: cmd
        run: |
          call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          dir
          mkdir build3
          cd build3
          cmake D:/a/a/a/llvm-project/llvm -GNinja ^
            -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;compiler-rt;lld;openmp;polly ^
            -DLLVM_BUILD_EXAMPLES=OFF ^
            -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_WERROR=OFF ^
            -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_TARGETS_TO_BUILD=X86 ^
            -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl ^
            -DCMAKE_INSTALL_PREFIX="D:/a/a/a/llvm-project/llvm/install3"
          cmake --build . --target install --config Release
          
      - uses: actions/upload-artifact@v2
        with: 
          name: llvm-14-msvc
          path: D:/a/a/a/llvm-project/llvm/install3
